num_to_classes = {0: 'astro-ph.CO',
                  1: 'astro-ph.EP',
                  2: 'astro-ph.GA',
                  3: 'astro-ph.HE',
                  4: 'astro-ph.IM',
                  5: 'astro-ph.SR',
                  6: 'astro-ph.all',
                  7: 'cond-mat.dis-nn',
                  8: 'cond-mat.mes-hall',
                  9: 'cond-mat.mtrl-sci',
                  10: 'cond-mat.other',
                  11: 'cond-mat.quant-gas',
                  12: 'cond-mat.soft',
                  13: 'cond-mat.stat-mech',
                  14: 'cond-mat.str-el',
                  15: 'cond-mat.supr-con',
                  16: 'cs.AI',
                  17: 'cs.AR',
                  18: 'cs.CC',
                  19: 'cs.CE',
                  20: 'cs.CG',
                  21: 'cs.CL',
                  22: 'cs.CR',
                  23: 'cs.CV',
                  24: 'cs.CY',
                  25: 'cs.DB',
                  26: 'cs.DC',
                  27: 'cs.DL',
                  28: 'cs.DM',
                  29: 'cs.DS',
                  30: 'cs.ET',
                  31: 'cs.FL',
                  32: 'cs.GL',
                  33: 'cs.GR',
                  34: 'cs.GT',
                  35: 'cs.HC',
                  36: 'cs.IR',
                  37: 'cs.IT',
                  38: 'cs.LG',
                  39: 'cs.LO',
                  40: 'cs.MA',
                  41: 'cs.MM',
                  42: 'cs.MS',
                  43: 'cs.NA',
                  44: 'cs.NE',
                  45: 'cs.NI',
                  46: 'cs.OH',
                  47: 'cs.OS',
                  48: 'cs.PF',
                  49: 'cs.PL',
                  50: 'cs.RO',
                  51: 'cs.SC',
                  52: 'cs.SD',
                  53: 'cs.SE',
                  54: 'cs.SI',
                  55: 'cs.SY',
                  56: 'econ.EM',
                  57: 'econ.GN',
                  58: 'econ.TH',
                  59: 'eess.AS',
                  60: 'eess.IV',
                  61: 'eess.SP',
                  62: 'eess.SY',
                  63: 'gr-qc',
                  64: 'hep-ex',
                  65: 'hep-lat',
                  66: 'hep-ph',
                  67: 'hep-th',
                  68: 'math-ph',
                  69: 'math.AC',
                  70: 'math.AG',
                  71: 'math.AP',
                  72: 'math.AT',
                  73: 'math.CA',
                  74: 'math.CO',
                  75: 'math.CT',
                  76: 'math.CV',
                  77: 'math.DG',
                  78: 'math.DS',
                  79: 'math.FA',
                  80: 'math.GM',
                  81: 'math.GN',
                  82: 'math.GR',
                  83: 'math.GT',
                  84: 'math.HO',
                  85: 'math.KT',
                  86: 'math.LO',
                  87: 'math.MG',
                  88: 'math.NA',
                  89: 'math.NT',
                  90: 'math.OA',
                  91: 'math.OC',
                  92: 'math.PR',
                  93: 'math.QA',
                  94: 'math.RA',
                  95: 'math.RT',
                  96: 'math.SG',
                  97: 'math.SP',
                  98: 'math.ST',
                  99: 'nlin.AO',
                  100: 'nlin.CD',
                  101: 'nlin.CG',
                  102: 'nlin.PS',
                  103: 'nlin.SI',
                  104: 'nucl-ex',
                  105: 'nucl-th',
                  106: 'physics.acc-ph',
                  107: 'physics.ao-ph',
                  108: 'physics.app-ph',
                  109: 'physics.atm-clus',
                  110: 'physics.atom-ph',
                  111: 'physics.bio-ph',
                  112: 'physics.chem-ph',
                  113: 'physics.class-ph',
                  114: 'physics.comp-ph',
                  115: 'physics.data-an',
                  116: 'physics.ed-ph',
                  117: 'physics.flu-dyn',
                  118: 'physics.gen-ph',
                  119: 'physics.geo-ph',
                  120: 'physics.hist-ph',
                  121: 'physics.ins-det',
                  122: 'physics.med-ph',
                  123: 'physics.optics',
                  124: 'physics.plasm-ph',
                  125: 'physics.pop-ph',
                  126: 'physics.soc-ph',
                  127: 'physics.space-ph',
                  128: 'q-bio.BM',
                  129: 'q-bio.CB',
                  130: 'q-bio.GN',
                  131: 'q-bio.MN',
                  132: 'q-bio.NC',
                  133: 'q-bio.OT',
                  134: 'q-bio.PE',
                  135: 'q-bio.QM',
                  136: 'q-bio.SC',
                  137: 'q-bio.TO',
                  138: 'q-fin.CP',
                  139: 'q-fin.EC',
                  140: 'q-fin.GN',
                  141: 'q-fin.MF',
                  142: 'q-fin.PM',
                  143: 'q-fin.PR',
                  144: 'q-fin.RM',
                  145: 'q-fin.ST',
                  146: 'q-fin.TR',
                  147: 'quant-ph',
                  148: 'stat.AP',
                  149: 'stat.CO',
                  150: 'stat.ME',
                  151: 'stat.ML',
                  152: 'stat.OT'}

classes_to_num = {'astro-ph.CO': 0,
                  'astro-ph.EP': 1,
                  'astro-ph.GA': 2,
                  'astro-ph.HE': 3,
                  'astro-ph.IM': 4,
                  'astro-ph.SR': 5,
                  'astro-ph.all': 6,
                  'cond-mat.dis-nn': 7,
                  'cond-mat.mes-hall': 8,
                  'cond-mat.mtrl-sci': 9,
                  'cond-mat.other': 10,
                  'cond-mat.quant-gas': 11,
                  'cond-mat.soft': 12,
                  'cond-mat.stat-mech': 13,
                  'cond-mat.str-el': 14,
                  'cond-mat.supr-con': 15,
                  'cs.AI': 16,
                  'cs.AR': 17,
                  'cs.CC': 18,
                  'cs.CE': 19,
                  'cs.CG': 20,
                  'cs.CL': 21,
                  'cs.CR': 22,
                  'cs.CV': 23,
                  'cs.CY': 24,
                  'cs.DB': 25,
                  'cs.DC': 26,
                  'cs.DL': 27,
                  'cs.DM': 28,
                  'cs.DS': 29,
                  'cs.ET': 30,
                  'cs.FL': 31,
                  'cs.GL': 32,
                  'cs.GR': 33,
                  'cs.GT': 34,
                  'cs.HC': 35,
                  'cs.IR': 36,
                  'cs.IT': 37,
                  'cs.LG': 38,
                  'cs.LO': 39,
                  'cs.MA': 40,
                  'cs.MM': 41,
                  'cs.MS': 42,
                  'cs.NA': 43,
                  'cs.NE': 44,
                  'cs.NI': 45,
                  'cs.OH': 46,
                  'cs.OS': 47,
                  'cs.PF': 48,
                  'cs.PL': 49,
                  'cs.RO': 50,
                  'cs.SC': 51,
                  'cs.SD': 52,
                  'cs.SE': 53,
                  'cs.SI': 54,
                  'cs.SY': 55,
                  'econ.EM': 56,
                  'econ.GN': 57,
                  'econ.TH': 58,
                  'eess.AS': 59,
                  'eess.IV': 60,
                  'eess.SP': 61,
                  'eess.SY': 62,
                  'gr-qc': 63,
                  'hep-ex': 64,
                  'hep-lat': 65,
                  'hep-ph': 66,
                  'hep-th': 67,
                  'math-ph': 68,
                  'math.AC': 69,
                  'math.AG': 70,
                  'math.AP': 71,
                  'math.AT': 72,
                  'math.CA': 73,
                  'math.CO': 74,
                  'math.CT': 75,
                  'math.CV': 76,
                  'math.DG': 77,
                  'math.DS': 78,
                  'math.FA': 79,
                  'math.GM': 80,
                  'math.GN': 81,
                  'math.GR': 82,
                  'math.GT': 83,
                  'math.HO': 84,
                  'math.KT': 85,
                  'math.LO': 86,
                  'math.MG': 87,
                  'math.NA': 88,
                  'math.NT': 89,
                  'math.OA': 90,
                  'math.OC': 91,
                  'math.PR': 92,
                  'math.QA': 93,
                  'math.RA': 94,
                  'math.RT': 95,
                  'math.SG': 96,
                  'math.SP': 97,
                  'math.ST': 98,
                  'nlin.AO': 99,
                  'nlin.CD': 100,
                  'nlin.CG': 101,
                  'nlin.PS': 102,
                  'nlin.SI': 103,
                  'nucl-ex': 104,
                  'nucl-th': 105,
                  'physics.acc-ph': 106,
                  'physics.ao-ph': 107,
                  'physics.app-ph': 108,
                  'physics.atm-clus': 109,
                  'physics.atom-ph': 110,
                  'physics.bio-ph': 111,
                  'physics.chem-ph': 112,
                  'physics.class-ph': 113,
                  'physics.comp-ph': 114,
                  'physics.data-an': 115,
                  'physics.ed-ph': 116,
                  'physics.flu-dyn': 117,
                  'physics.gen-ph': 118,
                  'physics.geo-ph': 119,
                  'physics.hist-ph': 120,
                  'physics.ins-det': 121,
                  'physics.med-ph': 122,
                  'physics.optics': 123,
                  'physics.plasm-ph': 124,
                  'physics.pop-ph': 125,
                  'physics.soc-ph': 126,
                  'physics.space-ph': 127,
                  'q-bio.BM': 128,
                  'q-bio.CB': 129,
                  'q-bio.GN': 130,
                  'q-bio.MN': 131,
                  'q-bio.NC': 132,
                  'q-bio.OT': 133,
                  'q-bio.PE': 134,
                  'q-bio.QM': 135,
                  'q-bio.SC': 136,
                  'q-bio.TO': 137,
                  'q-fin.CP': 138,
                  'q-fin.EC': 139,
                  'q-fin.GN': 140,
                  'q-fin.MF': 141,
                  'q-fin.PM': 142,
                  'q-fin.PR': 143,
                  'q-fin.RM': 144,
                  'q-fin.ST': 145,
                  'q-fin.TR': 146,
                  'quant-ph': 147,
                  'stat.AP': 148,
                  'stat.CO': 149,
                  'stat.ME': 150,
                  'stat.ML': 151,
                  'stat.OT': 152}

taxonomy = {'cs.AI': 'Artificial Intelligence',
            'cs.AR': 'Hardware Architecture',
            'cs.CC': 'Computational Complexity',
            'cs.CE': 'Computational Engineering, Finance, and Science',
            'cs.CG': 'Computational Geometry',
            'cs.CL': 'Computation and Language',
            'cs.CR': 'Cryptography and Security',
            'cs.CV': 'Computer Vision and Pattern Recognition',
            'cs.CY': 'Computers and Society',
            'cs.DB': 'Databases',
            'cs.DC': 'Distributed, Parallel, and Cluster Computing',
            'cs.DL': 'Digital Libraries',
            'cs.DM': 'Discrete Mathematics',
            'cs.DS': 'Data Structures and Algorithms',
            'cs.ET': 'Emerging Technologies',
            'cs.FL': 'Formal Languages and Automata Theory',
            'cs.GL': 'General Literature',
            'cs.GR': 'Graphics',
            'cs.GT': 'Computer Science and Game Theory',
            'cs.HC': 'Human-Computer Interaction',
            'cs.IR': 'Information Retrieval',
            'cs.IT': 'Information Theory',
            'cs.LG': 'Machine Learning',
            'cs.LO': 'Logic in Computer Science',
            'cs.MA': 'Multiagent Systems',
            'cs.MM': 'Multimedia',
            'cs.MS': 'Mathematical Software',
            'cs.NA': 'Numerical Analysis',
            'cs.NE': 'Neural and Evolutionary Computing',
            'cs.NI': 'Networking and Internet Architecture',
            'cs.OH': 'Other Computer Science',
            'cs.OS': 'Operating Systems',
            'cs.PF': 'Performance',
            'cs.PL': 'Programming Languages',
            'cs.RO': 'Robotics',
            'cs.SC': 'Symbolic Computation',
            'cs.SD': 'Sound',
            'cs.SE': 'Software Engineering',
            'cs.SI': 'Social and Information Networks',
            'cs.SY': 'Systems and Control',
            'econ.EM': 'Econometrics',
            'econ.GN': 'General Economics',
            'econ.TH': 'Theoretical Economics',
            'eess.AS': 'Audio and Speech Processing',
            'eess.IV': 'Image and Video Processing',
            'eess.SP': 'Signal Processing',
            'eess.SY': 'Systems and Control',
            'math.AC': 'Commutative Algebra',
            'math.AG': 'Algebraic Geometry',
            'math.AP': 'Analysis of PDEs',
            'math.AT': 'Algebraic Topology',
            'math.CA': 'Classical Analysis and ODEs',
            'math.CO': 'Combinatorics',
            'math.CT': 'Category Theory',
            'math.CV': 'Complex Variables',
            'math.DG': 'Differential Geometry',
            'math.DS': 'Dynamical Systems',
            'math.FA': 'Functional Analysis',
            'math.GM': 'General Mathematics',
            'math.GN': 'General Topology',
            'math.GR': 'Group Theory',
            'math.GT': 'Geometric Topology',
            'math.HO': 'History and Overview',
            'math.IT': 'Information Theory',
            'math.KT': 'K-Theory and Homology',
            'math.LO': 'Logic',
            'math.MG': 'Metric Geometry',
            'math.MP': 'Mathematical Physics',
            'math.NA': 'Numerical Analysis',
            'math.NT': 'Number Theory',
            'math.OA': 'Operator Algebras',
            'math.OC': 'Optimization and Control',
            'math.PR': 'Probability',
            'math.QA': 'Quantum Algebra',
            'math.RA': 'Rings and Algebras',
            'math.RT': 'Representation Theory',
            'math.SG': 'Symplectic Geometry',
            'math.SP': 'Spectral Theory',
            'math.ST': 'Statistics Theory',
            'astro-ph.all': 'Astrophysics',
            'astro-ph.CO': 'Cosmology and Nongalactic Astrophysics',
            'astro-ph.EP': 'Earth and Planetary Astrophysics',
            'astro-ph.GA': 'Astrophysics of Galaxies',
            'astro-ph.HE': 'High Energy Astrophysical Phenomena',
            'astro-ph.IM': 'Instrumentation and Methods for Astrophysics',
            'astro-ph.SR': 'Solar and Stellar Astrophysics',
            'cond-mat.dis-nn': 'Disordered Systems and Neural Networks',
            'cond-mat.mes-hall': 'Mesoscale and Nanoscale Physics',
            'cond-mat.mtrl-sci': 'Materials Science',
            'cond-mat.other': 'Other Condensed Matter',
            'cond-mat.quant-gas': 'Quantum Gases',
            'cond-mat.soft': 'Soft Condensed Matter',
            'cond-mat.stat-mech': 'Statistical Mechanics',
            'cond-mat.str-el': 'Strongly Correlated Electrons',
            'cond-mat.supr-con': 'Superconductivity',
            'gr-qc': 'General Relativity and Quantum Cosmology',
            'hep-ex': 'High Energy Physics - Experiment',
            'hep-lat': 'High Energy Physics - Lattice',
            'hep-ph': 'High Energy Physics - Phenomenology',
            'hep-th': 'High Energy Physics - Theory',
            'math-ph': 'Mathematical Physics',
            'nlin.AO': 'Adaptation and Self-Organizing Systems',
            'nlin.CD': 'Chaotic Dynamics',
            'nlin.CG': 'Cellular Automata and Lattice Gases',
            'nlin.PS': 'Pattern Formation and Solitons',
            'nlin.SI': 'Exactly Solvable and Integrable Systems',
            'nucl-ex': 'Nuclear Experiment',
            'nucl-th': 'Nuclear Theory',
            'physics.acc-ph': 'Accelerator Physics',
            'physics.ao-ph': 'Atmospheric and Oceanic Physics',
            'physics.app-ph': 'Applied Physics',
            'physics.atm-clus': 'Atomic and Molecular Clusters',
            'atom-ph.all': 'Atomic Physics',
            'physics.atom-ph': 'Atomic Physics',
            'physics.bio-ph': 'Biological Physics',
            'physics.chem-ph': 'Chemical Physics',
            'physics.class-ph': 'Classical Physics',
            'physics.comp-ph': 'Computational Physics',
            'physics.data-an': 'Data Analysis, Statistics and Probability',
            'physics.ed-ph': 'Physics Education',
            'physics.flu-dyn': 'Fluid Dynamics',
            'physics.gen-ph': 'General Physics',
            'physics.geo-ph': 'Geophysics',
            'physics.hist-ph': 'History and Philosophy of Physics',
            'physics.ins-det': 'Instrumentation and Detectors',
            'physics.med-ph': 'Medical Physics',
            'physics.optics': 'Optics',
            'physics.plasm-ph': 'Plasma Physics',
            'physics.pop-ph': 'Popular Physics',
            'physics.soc-ph': 'Physics and Society',
            'physics.space-ph': 'Space Physics',
            'quant-ph': 'Quantum Physics',
            'q-bio.BM': 'Biomolecules',
            'q-bio.CB': 'Cell Behavior',
            'q-bio.GN': 'Genomics',
            'q-bio.MN': 'Molecular Networks',
            'q-bio.NC': 'Neurons and Cognition',
            'q-bio.OT': 'Other Quantitative Biology',
            'q-bio.PE': 'Populations and Evolution',
            'q-bio.QM': 'Quantitative Methods',
            'q-bio.SC': 'Subcellular Processes',
            'q-bio.TO': 'Tissues and Organs',
            'q-fin.CP': 'Computational Finance',
            'q-fin.EC': 'Economics',
            'q-fin.GN': 'General Finance',
            'q-fin.MF': 'Mathematical Finance',
            'q-fin.PM': 'Portfolio Management',
            'q-fin.PR': 'Pricing of Securities',
            'q-fin.RM': 'Risk Management',
            'q-fin.ST': 'Statistical Finance',
            'q-fin.TR': 'Trading and Market Microstructure',
            'stat.AP': 'Applications',
            'stat.CO': 'Computation',
            'stat.ME': 'Methodology',
            'stat.ML': 'Machine Learning',
            'stat.OT': 'Other Statistics',
            'stat.TH': 'Statistics Theory'}
